spring.application.name=WorDrop

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/wordrop_db
spring.datasource.username=postgres
spring.datasource.password=wordropdatabase85246
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

wordrop.jwt.secret=w&Z4j@Z(i>9Zf<9*{Un.?MrTENzIF&AW_7BKWf5N
wordrop.jwt.lifetime=2592000000

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true