spring.application.name=WorDrop

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/wordrop_db
spring.datasource.username=postgres
spring.datasource.password=wordropdatabase85246
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true